// <auto-generated />
using System;
using Diario_de_Bordo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Diario_de_Bordo.Migrations
{
    [DbContext(typeof(DiarioContext))]
    [Migration("20251027135152_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Diario_de_Bordo.Models.CQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cliente");

                    b.Property<string>("ComentarioGeral")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date_field")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Date_field");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Fase");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Modelo");

                    b.Property<string>("OP")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("OP");

                    b.Property<string>("Programa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Programa");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Responsavel");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("Status");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Turno");

                    b.HasKey("Id");

                    b.ToTable("tbl_cq", (string)null);
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.CQEvidencia", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("comentario")
                        .HasColumnType("text");

                    b.Property<int>("cq_id")
                        .HasColumnType("integer")
                        .HasColumnName("cq_id");

                    b.Property<string>("evidencia")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidencia");

                    b.Property<string>("item")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("posto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("posto");

                    b.Property<string>("resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("cq_id");

                    b.ToTable("tbl_cq_evidencia", (string)null);
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.PartRequest", b =>
                {
                    b.Property<string>("RequestId")
                        .HasColumnType("text")
                        .HasColumnName("request_id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("partnumber");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.HasKey("RequestId");

                    b.ToTable("tbl_partrequest");
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.Report", b =>
                {
                    b.Property<int>("report_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("report_id"));

                    b.Property<string>("classificacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date_field")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("linha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("maquina")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("technician")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("report_id");

                    b.ToTable("tbl_report");
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.Stencil", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("cliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cliente");

                    b.Property<string>("cod_fabricante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cod_fabricante");

                    b.Property<string>("data_fabricacao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_fabricacao");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("fabricante")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fabricante");

                    b.Property<string>("num_stencil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("num_stencil");

                    b.HasKey("id");

                    b.ToTable("tbl_stencil", (string)null);
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.Stencil_Check", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("Stencilid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("check_date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<string>("comentario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<string>("evidence_unc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence_unc");

                    b.Property<int>("id_stencil")
                        .HasColumnType("integer")
                        .HasColumnName("id_stencil");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("user")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user");

                    b.HasKey("id");

                    b.HasIndex("Stencilid");

                    b.HasIndex("id_stencil");

                    b.ToTable("tbl_stencilcheck", (string)null);
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.CQEvidencia", b =>
                {
                    b.HasOne("Diario_de_Bordo.Models.CQ", "CQ")
                        .WithMany("Evidencias")
                        .HasForeignKey("cq_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CQ");
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.Stencil_Check", b =>
                {
                    b.HasOne("Diario_de_Bordo.Models.Stencil", "Stencil")
                        .WithMany()
                        .HasForeignKey("Stencilid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Diario_de_Bordo.Models.Stencil", null)
                        .WithMany("Stencil_Checks")
                        .HasForeignKey("id_stencil")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stencil");
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.CQ", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Diario_de_Bordo.Models.Stencil", b =>
                {
                    b.Navigation("Stencil_Checks");
                });
#pragma warning restore 612, 618
        }
    }
}
